apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: workflow-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: workflow-worker # Must match your Deployment name
  minReplicaCount: 1     # Scales down to zero if no messages!
  maxReplicaCount: 5   # Maximum 5 pods during a rush
  cooldownPeriod:  30
  pollingInterval: 5
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.ap-south-1.amazonaws.com/785640717631/patient-intake-queue
        queueLength: "5" # Target 5 messages per pod
        awsRegion: ap-south-1
      authenticationRef:
        name: keda-aws-credentials