apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-aws-credentials
  namespace: default
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: aws-sqs-credentials
      key: access-key
    - parameter: awsSecretAccessKey
      name: aws-sqs-credentials
      key: secret-key