apiVersion: v1
kind: Service
metadata:
  name: patient-intake-service
  annotations:
    # THIS IS THE FIX: Tells AWS to make it Public
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # Ensure your subnets are still listed
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-033e2ab2356dbd562, subnet-0c366c03e51921c0e"
spec:
  type: LoadBalancer
  selector:
    app: patient-intake
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30880