spring:
  application:
    name: patient-intake-service
  datasource:
    url: jdbc:mysql://healthcare-db.cnsu2okwc6v9.ap-south-1.rds.amazonaws.com:3306/healthcare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Jaiganesha2109
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8888

aws:
  region: ${AWS_REGION:ap-south-1}
  account-id: ${AWS_ACCOUNT_ID:000000000000}
  sqs:
    # This builds the URL dynamically without hardcoding your ID
    queue-url: https://sqs.${aws.region}.amazonaws.com/785640717631/patient-intake-queue
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:default-access-key}
    secret-key: ${AWS_SECRET_ACCESS_KEY:default-secret-key}