name: CI/CD Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: 785640717631
  PATIENT_REPO: patient-intake-service
  WORKFLOW_REPO: workflow-worker

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build entire project
        run: mvn -U clean install -DskipTests

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build patient-intake image
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PATIENT_REPO:latest ./patient-intake-service
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$PATIENT_REPO:latest

      - name: Build workflow-worker image
        run: |
          docker build -t $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$WORKFLOW_REPO:latest ./workflow-worker
          docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$WORKFLOW_REPO:latest